### ISSUE TITLE
node_module error

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-experiments#20]
@dannycoates I'm getting this error when the content server tries to load able experiments:

```
eslint [options] file.js [file.js] [dir]

Options:
  -h, --help                  Show help
  -c, --config path::String   Use configuration from this file
  --rulesdir [path::String]   Use additional rules from this directory
  -f, --format String         Use a specific output format - default: stylish
  -v, --version               Outputs the version number
  --reset                     Set all default rules to off - default: false
  --no-eslintrc               Disable use of configuration from .eslintrc
  --env [String]              Specify environments
  --ext [String]              Specify JavaScript file extensions - default: .js
  --plugin [String]           Specify plugins
  --global [String]           Define global variables
  --rule Object               Specify rules
  --ignore-path path::String  Specify path of ignore file
  --no-ignore                 Disable use of .eslintignore
  --ignore-pattern String     Pattern of files to ignore (in addition to those in .eslintignore)
  --no-color                  Disable color in piped output
  -o, --output-file path::String  Specify file to write report to
  --quiet                     Report errors only - default: false
  --stdin                     Lint code provided on <STDIN> - default: false
  --stdin-filename String     Specify filename to process STDIN as
  --init                      Run config initialization wizard - default: false
ok
fxa-content-server.route.500.ERROR: Error: Cannot find module 'tap'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/vladikoff/mozilla/fxa-content-experiments/node_modules/eslint/node_modules/concat-stream/node_modules/readable-stream/node_modules/process-nextick-args/test.js:1:74)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
55

/Users/vladikoff/mozilla/fxa-content-experiments/node_modules/eslint/node_modules/escope/src/definition.js:25
import Variable from './variable';
^^^^^^
Usage:
   esparse [options] file.js

Available options:

  --comment      Gather all line and block comments in an array
  --loc          Include line-column location info for each syntax node
  --range        Include index-based range for each syntax node
  --raw          Display the raw value of literals
  --tokens       List all tokens in an array
  --tolerant     Tolerate errors on a best-effort basis (experimental)
  -v, --version  Shows program version

fxa-content-server killed, exiting

Done, without errors.

```

Does this mean that the `node_modules` directory is being treated as an experiment directory? 
Should we exclude it or something?

**Comment by dannycoates** [comment]
yes

**Comment by vladikoff** [comment]
@dannycoates how should be exclude this, any other ideas?

**Comment by dannycoates** [comment]
we'll need to exclude it from https://github.com/dannycoates/able/blob/master/project.js#L137
